
/**:
  ros__parameters:
    engage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: true
      buttons: [5, 1]
    disengage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: false
      buttons: [5, 2]
      
    joy_topic: /joy
      twist_topic: /cmd_vel
      move:
        forward:
          axis: 1
          scale: 3.5
          deadzone: 0.0
        reverse:
          axis: 1
          scale: 3.5
          deadzone: 0.0  
        left:
          axis: 0
          scale: 3.5
          deadzone: 0.0
        right:
          axis: 0
          scale: 3.5
          deadzone: 0.0
      turn:
        left:
          axis: 5
          scale: 10.0
          deadzone: 0.0
          offset: 1.0
        right:
          axis: 4
          scale: -10.0
          deadzone: 0.0
          offset: 1.0
          
joystick:
  ros__parameters:
    joy_topic: /joy
    dev: /dev/input/js0
    deadzone: 0.2
