# Logitech F710 wireless controller
# Deadman (enable) button: Right Trigger
# D<>X button (located on the back panel) must be set to D
/**:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: [7]  # RT
      axis_mappings:
        linear-x:
          axis: 3
          scale: 0.5
          offset: 0
        linear-y:
          axis: 4
          scale: 0.5
          offset: 0
        angular-z:
          axis: 0
          scale: 0.8
          offset: 0
    yellow:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7,3]  # RT
      message_value:
        color-r:
          value: 1.0
        color-g:
          value: 1.0
    blue:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7,0]  # RT
      message_value:
        color-b:
          value: 1.0
    green:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7,1]  # RT
      message_value:
        color-g:
          value: 1.0
    red:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7,2]  # RT
      message_value:
        color-r:
          value: 1.0
    off:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [7,5]  # RT
      message_value:
        effect:
          value: 0
    close_gripper:
      type: action
      interface_type: robomaster_msgs/action/GripperControl
      action_name: gripper
      action_goal:
        target_state: 2
      buttons: [6, 2]
    open_gripper:
      type: action
      interface_type: robomaster_msgs/action/GripperControl
      action_name: gripper
      action_goal:
        target_state: 1
      buttons: [6, 0]
    comarm:
      type: topic
      interface_type: "geometry_msgs/msg/Vector3"
      topic_name: cmd_arm
      deadman_buttons: [6]  # RT
      axis_mappings:
        x:
          axis: 3
          scale: 0.2
          offset: 0
        z:
          axis: 1
          scale: 0.2
          offset: 0
    engage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: true
      buttons: [5, 1]
    disengage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: false
      buttons: [5, 2]
